/**
 * What a scan finds, and the seam it comes through.
 *
 * ── THE PORT, AND WHY THE LIBRARY HAS NO DRIVER DEPENDENCY ──────────────────────────────
 * `SqlExecutor` is the whole contract: run a statement with parameters, get rows back. That is all a
 * schema probe needs, and keeping it that small has three consequences worth the discipline:
 *
 *   · **this library depends on no database driver.** A deployment supplies the adapter — for SQL Server
 *     that is about fifteen lines around the `mssql` package, shown in the doc — and nothing here
 *     changes when the driver version does;
 *   · **the introspection SQL is reviewable on its own.** It is in `mssql-probe.ts`, in one place, and a
 *     DBA can read it without reading TypeScript;
 *   · **every path is testable without a server.** The fixture executor in `fixture-source.ts` answers
 *     the same statements, so the inference, the drift detection and the UI are all exercised for real.
 *
 * ── AND WHY THE SCAN RESULT IS ITS OWN TYPE ─────────────────────────────────────────────
 * `PhysicalSchema` is deliberately *not* a catalog. It is what the database says about itself: tables,
 * columns, SQL types, keys, foreign keys, row counts. Turning that into business vocabulary is a
 * separate step with separate judgement (`infer.ts`), and separating them is what makes a re-scan
 * diffable — the physical shape is a fact, and comparing facts is how drift is detected.
 */

/** Rows from one statement. Deliberately loose: a probe knows the shape it asked for. */
export type SqlRow = Readonly<Record<string, unknown>>;

/**
 * The one thing a deployment must implement.
 *
 * Parameters are named, because that is what SQL Server's driver takes and positional placeholders in a
 * dialect that uses `@name` invite the mistake this interface exists to prevent.
 */
export interface SqlExecutor {
  /** A label for logs and the audit record — "mssql://host/db", never a connection string. */
  readonly label: string;
  query(sql: string, params?: Readonly<Record<string, unknown>>): Promise<SqlRow[]>;
}

export interface PhysicalColumn {
  name: string;
  ordinal: number;
  /** The SQL type as the server reports it: `nvarchar`, `decimal`, `datetime2`… */
  sqlType: string;
  maxLength?: number;
  precision?: number;
  scale?: number;
  nullable: boolean;
  /** True when the column is part of the table's primary key. */
  isKey: boolean;
  /** Generated by the server — identity or computed. A page may read it and never write it. */
  isGenerated: boolean;
  defaultExpression?: string;
  /** Distinct values, when a low-cardinality probe ran and found few enough to be an enum. */
  distinctValues?: string[];
  /** Values a CHECK constraint restricts the column to, parsed from its definition. */
  checkValues?: string[];
}

export interface PhysicalForeignKey {
  name: string;
  fromTable: string;
  fromColumns: string[];
  toTable: string;
  toColumns: string[];
}

export interface PhysicalTable {
  /** `schema.table`, which is the identity a scan and a re-scan agree on. */
  ref: string;
  schema: string;
  name: string;
  /** A view rather than a table. Scanned the same way and worth knowing: no row count, no keys. */
  isView: boolean;
  /** From `sys.partitions` — an estimate, and treated as one. */
  approxRows?: number;
  columns: PhysicalColumn[];
  primaryKey: string[];
  foreignKeys: PhysicalForeignKey[];
  /** The extended property or comment the DBA left, where the dialect has one. */
  description?: string;
}

export interface PhysicalSchema {
  sourceId: string;
  kind: string;
  database: string;
  /** Which schemas were asked for — a scan of two of five is not a scan of the database. */
  schemas: string[];
  tables: PhysicalTable[];
  scannedAt: string;
  /** The server's own version string, recorded because inference depends on the dialect's vintage. */
  serverVersion?: string;
  /**
   * Whether this scan sampled values to find enumerations.
   *
   * Recorded because it changes what the scan can see, and a diff that does not know it reports a false
   * alarm: re-scanning without sampling, after a scan that sampled, makes every discovered code list
   * look as though it vanished from the database. The flag lets drift detection say "this scan did not
   * look" instead of "the constraint is gone".
   */
  sampledEnumerations: boolean;
  /** What the scan could not do, in the steward's language. Never empty silently. */
  warnings: string[];
}

export interface ProbeOptions {
  /**
   * Sample low-cardinality columns to find enumerations.
   *
   * Off by default, and the default matters: it is the only part of a scan that reads *data* rather than
   * metadata. A steward turns it on knowingly, because "the values in this column" is a disclosure in a
   * way "this column exists" is not — and because on a billion-row table it is an expensive question.
   */
  sampleEnumerations: boolean;
  /** A column with at most this many distinct values is treated as an enumeration. */
  maxEnumValues: number;
  /** Skip enumeration sampling on tables larger than this, whatever the setting above says. */
  enumSampleRowLimit: number;
  /** Refuse a scan that would return more than this many tables, rather than hanging a UI. */
  maxTables: number;
}

export const DEFAULT_PROBE_OPTIONS: ProbeOptions = {
  sampleEnumerations: false,
  maxEnumValues: 24,
  enumSampleRowLimit: 5_000_000,
  maxTables: 500,
};

/** A probe for one dialect. */
export interface SchemaProbe {
  readonly kind: string;
  scan(executor: SqlExecutor, options?: Partial<ProbeOptions>): Promise<PhysicalSchema>;
}
