/**
 * Emit the fixture's Opus EDM schema as real SQL Server DDL.
 *
 * ── WHY GENERATE IT RATHER THAN HAND-WRITE IT ───────────────────────────────────────────
 * The point of this script is a comparison, and the comparison only means something if both sides
 * describe the same database. Generating the DDL from `OPUS_EDM_FIXTURE` guarantees the *logical*
 * schema matches; what it deliberately does not guarantee is how SQL Server *reports* that schema —
 * `max_length` in bytes, `is_computed`, the estimate in `sys.partitions`, the exact text a CHECK
 * constraint is stored as. Those come from the server, and a discrepancy between scanning the real
 * database and scanning the fixture is therefore a real finding about the fixture's fidelity.
 *
 * Hand-writing the DDL would test the same thing, plus my ability to transcribe eleven tables
 * without a typo — and a typo would show up as a fixture-fidelity failure that is really a
 * transcription failure, which is the least useful kind of red test.
 *
 * ── ROW COUNTS ──────────────────────────────────────────────────────────────────────────
 * The fixture claims a 240-million-row child table, and this does not insert 240 million rows. It
 * cannot: cost class, the unfiltered-query threshold and drift's proportional row-count test all key
 * off `sys.partitions`, which reports what is there. So the script emits the counts as a comment and
 * the comparison excludes `approxRows`, saying so rather than quietly passing.
 *
 * Usage:
 *   node tools/fixture-ddl.mjs > /tmp/opus-edm.sql
 */

import { OPUS_EDM_FIXTURE } from '../libs/catalog-ingest/src/fixture-source.ts';

const lines = [];
const out = (text = '') => lines.push(text);

out('/*');
out(' * Opus EDM — the schema this platform scans, as SQL Server DDL.');
out(' *');
out(' * GENERATED by tools/fixture-ddl.mjs from libs/catalog-ingest/src/fixture-source.ts.');
out(' * Edit the fixture, not this file.');
out(' */');
out();
out("IF DB_ID('OpusEDM') IS NULL CREATE DATABASE [OpusEDM];");
out('GO');
out('USE [OpusEDM];');
out('GO');
out();

const schemas = [...new Set(OPUS_EDM_FIXTURE.tables.map((table) => table.schema))].sort();
for (const schema of schemas) {
  out(`IF SCHEMA_ID('${schema}') IS NULL EXEC('CREATE SCHEMA [${schema}]');`);
}
out('GO');
out();

/*
  Every foreign key goes before any table is dropped, so the script is re-runnable.

  Without this, the second run fails on the first table another table points at — and a setup script
  that only works against an empty database is one somebody has to remember a caveat about.
*/
out('-- Drop every foreign key first, so this script can be run again.');
out(`DECLARE @drop nvarchar(max) = N'';
SELECT @drop = @drop + N'ALTER TABLE [' + s.name + N'].[' + t.name + N'] DROP CONSTRAINT [' + f.name + N'];' + CHAR(10)
FROM sys.foreign_keys f
JOIN sys.tables t ON t.object_id = f.parent_object_id
JOIN sys.schemas s ON s.schema_id = t.schema_id;
EXEC sp_executesql @drop;`);
out('GO');
out();

/** `nvarchar` reports twice its declared length in `sys.columns`, so halve it going the other way. */
function declaration(column) {
  const type = column.sqlType;
  const bytes = column.maxLength;

  if (type === 'nvarchar' || type === 'nchar') {
    if (bytes === -1) return `${type}(max)`;
    return `${type}(${bytes / 2})`;
  }
  if (type === 'varchar' || type === 'char' || type === 'binary' || type === 'varbinary') {
    return bytes === -1 ? `${type}(max)` : `${type}(${bytes})`;
  }
  if (type === 'decimal' || type === 'numeric') {
    return `${type}(${column.precision},${column.scale})`;
  }
  // datetime2(3), time(0) — the scale is the fractional-seconds precision.
  if ((type === 'datetime2' || type === 'time' || type === 'datetimeoffset') && column.scale !== undefined) {
    return `${type}(${column.scale})`;
  }
  return type;
}

/*
  Computed columns need an expression, and which column is computed is not something the fixture
  records — only that it is `generated`, which covers identity too. An integer identity is an
  identity; anything else generated is computed, and the expression is a plausible one. It only has
  to make the server report `is_computed`, which is the fact under test.
*/
const COMPUTED = {
  'processing.FILE_LOAD.ROWS_PENDING': '([ROWS_RECEIVED] - [ROWS_ACCEPTED] - [ROWS_REJECTED])',
};

/**
 * A view column, typed, and nullable exactly as the fixture says.
 *
 * `CAST(NULL AS int)` is provably null, so SQL Server reports the column nullable — which made every
 * column of the fixture's view disagree with the fixture, four differences that were about this
 * generator rather than about the schema. Wrapping a non-nullable one in `ISNULL(…, literal)` makes it
 * provably *not* null, and the server reports it as declared.
 */
function viewExpression(column) {
  const typed = `CAST(NULL AS ${declaration(column)})`;
  if (column.nullable) return typed;
  return `ISNULL(${typed}, ${zeroLiteral(column)})`;
}

/** A value of the column's own type that is never null. Its content is irrelevant: the view returns no rows. */
function zeroLiteral(column) {
  const type = column.sqlType;
  if (['nvarchar', 'nchar', 'varchar', 'char', 'text', 'ntext', 'sysname'].includes(type)) {
    return `CAST(N'' AS ${declaration(column)})`;
  }
  if (['date', 'datetime', 'datetime2', 'smalldatetime', 'datetimeoffset'].includes(type)) {
    return `CAST('19000101' AS ${declaration(column)})`;
  }
  if (type === 'time') return `CAST('00:00:00' AS ${declaration(column)})`;
  if (type === 'uniqueidentifier') return `CAST('00000000-0000-0000-0000-000000000000' AS ${type})`;
  // Numerics and bit.
  return `CAST(0 AS ${declaration(column)})`;
}

function isIdentity(table, column) {
  if (!column.generated) return false;
  if (COMPUTED[`${table.schema}.${table.name}.${column.name}`]) return false;
  return ['int', 'bigint', 'smallint', 'tinyint'].includes(column.sqlType);
}

// ── tables, then foreign keys, so declaration order does not matter ────────────────────
const tables = OPUS_EDM_FIXTURE.tables.filter((table) => !table.isView);
const views = OPUS_EDM_FIXTURE.tables.filter((table) => table.isView);

for (const table of tables) {
  const target = `[${table.schema}].[${table.name}]`;
  out(`-- ${target}${table.rows ? `  (~${table.rows.toLocaleString()} rows in production)` : ''}`);
  out(`IF OBJECT_ID('${table.schema}.${table.name}', 'U') IS NOT NULL DROP TABLE ${target};`);
  out(`CREATE TABLE ${target} (`);

  const parts = [];
  for (const column of table.columns) {
    const computed = COMPUTED[`${table.schema}.${table.name}.${column.name}`];
    if (computed) {
      parts.push(`  [${column.name}] AS ${computed}`);
      continue;
    }
    let part = `  [${column.name}] ${declaration(column)}`;
    if (isIdentity(table, column)) part += ' IDENTITY(1,1)';
    part += column.nullable ? ' NULL' : ' NOT NULL';
    if (column.defaultExpression) part += ` DEFAULT ${column.defaultExpression}`;
    if (column.check) part += ` CHECK (${column.check})`;
    parts.push(part);
  }
  if (table.primaryKey?.length) {
    parts.push(
      `  CONSTRAINT [PK_${table.schema}_${table.name}] PRIMARY KEY (${table.primaryKey
        .map((column) => `[${column}]`)
        .join(', ')})`,
    );
  }
  out(parts.join(',\n'));
  out(');');

  if (table.description) {
    /*
      The description is an extended property, which is where SQL Server keeps a comment — and the
      scan reads it, so it has to be set the same way rather than as a `--` comment the server
      cannot see.
    */
    out(
      `EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'${table.description.replace(/'/g, "''")}',` +
        ` @level0type = N'SCHEMA', @level0name = N'${table.schema}',` +
        ` @level1type = N'TABLE',  @level1name = N'${table.name}';`,
    );
  }
  out('GO');
  out();
}

out('-- Foreign keys, after every table exists.');
for (const table of tables) {
  for (const key of table.foreignKeys ?? []) {
    const [toSchema, toTable] = key.toTable.split('.');
    if (!OPUS_EDM_FIXTURE.tables.some((entry) => entry.schema === toSchema && entry.name === toTable)) {
      // The deliberate dangling reference: a foreign key to a schema outside the scan.
      out(`-- ${key.name} targets ${key.toTable}, which is outside the scanned schemas.`);
      out(`IF SCHEMA_ID('${toSchema}') IS NULL EXEC('CREATE SCHEMA [${toSchema}]');`);
      out(
        `IF OBJECT_ID('${toSchema}.${toTable}', 'U') IS NULL CREATE TABLE [${toSchema}].[${toTable}] (` +
          `${key.toColumns.map((column) => `[${column}] int NOT NULL`).join(', ')}, ` +
          `CONSTRAINT [PK_${toSchema}_${toTable}] PRIMARY KEY (${key.toColumns.map((c) => `[${c}]`).join(', ')}));`,
      );
    }
    out(
      `ALTER TABLE [${table.schema}].[${table.name}] ADD CONSTRAINT [${key.name}] FOREIGN KEY (` +
        `${key.columns.map((column) => `[${column}]`).join(', ')}) REFERENCES [${toSchema}].[${toTable}] (` +
        `${key.toColumns.map((column) => `[${column}]`).join(', ')});`,
    );
  }
}
out('GO');
out();

for (const view of views) {
  out(`-- ${view.schema}.${view.name} — a view, with no key of its own.`);
  out(`IF OBJECT_ID('${view.schema}.${view.name}', 'V') IS NOT NULL DROP VIEW [${view.schema}].[${view.name}];`);
  // CREATE VIEW must be the first statement in its batch, so the drop gets its own.
  out('GO');
  out(`CREATE VIEW [${view.schema}].[${view.name}] AS`);
  /*
    Typed rather than derived from the tables.

    A view's reported column types are whatever its SELECT produces, and the scan reads them the same
    way it reads a table's — so the cast list is how the view comes out with the columns the fixture
    claims. Deriving it from a real aggregate query would be prettier and would report the aggregate's
    types, not the declared ones.
  */
  out(
    `SELECT ${view.columns.map((column) => `${viewExpression(column)} AS [${column.name}]`).join(', ')}`,
  );
  out('WHERE 1 = 0;');
  // The view body runs to the end of the batch, so anything after it needs a new one.
  out('GO');
  if (view.description) {
    out(
      `EXEC sp_addextendedproperty @name = N'MS_Description', @value = N'${view.description.replace(/'/g, "''")}',` +
        ` @level0type = N'SCHEMA', @level0name = N'${view.schema}',` +
        ` @level1type = N'VIEW',   @level1name = N'${view.name}';`,
    );
  }
  out('GO');
  out();
}

/*
  A read-only login, because the scanner claims to be one.

  `db_datareader` plus `VIEW DEFINITION` is exactly what a scan needs and no more: metadata, and
  SELECT for the opt-in enumeration sample. A deployment's DBA is the audience for these four lines —
  they are the answer to "what are you asking me to grant".
*/
out('-- The login a scan should use. Read-only, deliberately.');
out("IF SUSER_ID('opus_scanner') IS NULL CREATE LOGIN [opus_scanner] WITH PASSWORD = N'Sc4n!OpusEdm2026', CHECK_POLICY = OFF;");
out("IF USER_ID('opus_scanner') IS NULL CREATE USER [opus_scanner] FOR LOGIN [opus_scanner];");
out('ALTER ROLE [db_datareader] ADD MEMBER [opus_scanner];');
out('GRANT VIEW DEFINITION TO [opus_scanner];');
out('GO');

process.stdout.write(lines.join('\n') + '\n');
